Split traces properly, so that every expression has a unique trace
saser/cakeml pull request #25
Opened 2017-04-20 11:47 UTC by hjorthjort

At some points in `source_to_mod` and `exh_to_pat` we created many expressions with the same trace. This pull request fixes that.

2017-04-20 13:05 UTC, Holmus requested changes

2017-04-20 13:05 UTC, Holmus commented on compiler/backend/exh_to_patScript.sml
> +     | _ => If t e1 e2 e3)`;
A bit confusing to use the name t both for the boolean and the trace

2017-04-20 13:05 UTC, Holmus commented on compiler/backend/source_to_modScript.sml
> +      Fun t1 x (compile_exp t (nsBind x (Var_local t1 x) env) e))
Assuming Var_local should have t2, otherwise this achieves no change

2017-04-20 15:16 UTC, myreen commented
The `pat_tups` function produces traces `t`, `mk_cons ... t`, `mk_cons ... (mk_cons ... t)`, `mk_cons ... (mk_cons ... (mk_cons ... t))`. To me this is wrong. A trace should either pass over unchanged or the traces in the next language should all be of the form `mk_cons ... t`, if `t` is the original trace. I don't think you want traces to be prefixes of other traces in the same language.

2017-04-21 12:49 UTC, hjorthjort commented
Completely right, Magnus. It was supposed to just add a number with `mk_cons t n`, where `n` would shrink for every iteration. But by overshadowing `t` in the `let` part causes the effect you described. This is fixed now by creating `t'`

```
val pat_tups_def = Define`
  (pat_tups t [] = [])
  /\
  (pat_tups t (x::xs) =
    let t' = mk_cons t ((LENGTH xs) + 1) in
      (x, Var_local t' x)::pat_tups t xs)`;
```

2017-04-21 12:50 UTC, hjorthjort commented on compiler/backend/source_to_modScript.sml
> +      Fun t1 x (compile_exp t (nsBind x (Var_local t1 x) env) e))
Yes, exactly. Good catch.

2017-04-21 12:50 UTC, hjorthjort commented on compiler/backend/exh_to_patScript.sml
> +     | _ => If t e1 e2 e3)`;
Completely right. Changing back.

2017-04-25 09:03 UTC, merged